export {default as TitleText} from './atomics/Texts/TitleText'
export {default as TaskText} from './atomics/Texts/TaskText'
export {default as AddTaskButton} from './atomics/Buttons/AddTaskButton'
export {default as FinishTaskButton} from './atomics/Buttons/FinishTaskButton'
export {default as Tab} from './atomics/Tabs/Tab'
export {default as StarIcon} from './atomics/Icons/StarIcon'
export {default as InputTask} from './atomics/Input/InputTask'
export {default as Task} from './organisms/Task'